[pytest]
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %d-%m-%Y %H:%M:%S
minversion = 7.0
addopts = -v --asyncio-mode=auto --cov=app --cov-report=term-missing
testpaths = tests
python_paths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    unit: unit tests
    integration_no_yt: integration tests without youtube
    asyncio: mark test as an async test
    integration: marks tests as integration tests