# Test your FastAPI endpoints

### Login to get token
POST http://127.0.0.1:8000/auth/token
Content-Type: application/x-www-form-urlencoded

username = your_username &
password = your_password

### Use the token from the login response in subsequent requests
@authToken = your_token_here

### short youtube video
POST http://127.0.0.1:8000/api/youtube/transcribe
Accept: application/json
Authorization: Bearer {{authToken}}

{
"url": "https://www.youtube.com/watch?v=WuciqTSbewY"
}

### short yt summarize
POST http://127.0.0.1:8000/api/youtube/summarize
Accept: application/json
Authorization: Bearer {{authToken}}

{
"url": "https://www.youtube.com/watch?v=WuciqTSbewY",
"type": "tldr",
"lang": "pl"
}

### long youtube video
POST http://127.0.0.1:8000/api/youtube/transcribe
Accept: application/json
Authorization: Bearer {{authToken}}

{
"url": "https://www.youtube.com/watch?v=jModalnvP8Q"
}

### AUDIO summarize short
POST http://127.0.0.1:8000/api/audio/summary
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="uploaded_file"; filename="audio_short.mp3"

< ./resources/audio_short.mp3
--boundary
Content-Disposition: form-data; name="type"

detailed
--boundary
Content-Disposition: form-data; name="lang"

pl