name: av-summarizer

services:
  av-summarizer-py:
    image: michmzr/av-summarizer-py:latest
    container_name: av-summarizer-py
    ports:
      - "8086:8086"
    volumes:
      - /var/lib/av-summarizer-py/data:/data/downloads
    restart: unless-stopped
    env_file: "av-summ.env"
    labels:
      io.portainer.accesscontrol.public  
    depends_on:
      - db

  db:
    image: postgres:17
    env_file: "av-summ.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      io.portainer.accesscontrol.public
    ports:
      - "5432:5432"

volumes:
  postgres_data:
