name: Feature

on:
  push:
    branches: [ "issue-*"]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/reusable-setup-test.yml
    secrets:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PROXY_SERVERS: ${{ secrets.PROXY_SERVERS }}