name: Reusable Setup and Test

on:
  workflow_call:
    secrets:
      JWT_SECRET_KEY:
        required: true
      OPENAI_API_KEY:
        required: true
      PROXY_SERVERS:
        required: true

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv

      - uses: actions/cache@v1
        id: cache-pipenv
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --python "${{ steps.setup-python.outputs.python-path }}"

      - name: Run migrations
        run: |
          sleep 5
          pipenv run alembic upgrade head
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          IS_LOCAL: true
          LANGCHAIN_TRACING_V2: false
          LANGCHAIN_ENDPOINT: ""
          LANGCHAIN_PROJECT: ""
          LANGCHAIN_API_KEY: ""

      - name: Unit & integrational testing
        run: |
          pipenv install pytest-asyncio
          PYTHONPATH=$PWD pipenv run pytest --verbose -v
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_NAME: test_db
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROXY_SERVERS: ${{ secrets.PROXY_SERVERS }}
          SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          IS_LOCAL: true
          LANGCHAIN_TRACING_V2: false
          LANGCHAIN_ENDPOINT: ""
          LANGCHAIN_PROJECT: ""
          LANGCHAIN_API_KEY: "" 